// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseForPC(arg1) {
  return window['go']['main']['App']['BrowseForPC'](arg1);
}

export function DiscoverClients() {
  return window['go']['main']['App']['DiscoverClients']();
}

export function GetClientInfo(arg1) {
  return window['go']['main']['App']['GetClientInfo'](arg1);
}

export function GetScreenshot(arg1) {
  return window['go']['main']['App']['GetScreenshot'](arg1);
}

export function GetStreamFrame(arg1) {
  return window['go']['main']['App']['GetStreamFrame'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function StartScreenStream(arg1, arg2) {
  return window['go']['main']['App']['StartScreenStream'](arg1, arg2);
}

export function StopScreenStream(arg1) {
  return window['go']['main']['App']['StopScreenStream'](arg1);
}
