// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BrowseForPC(arg1:string):Promise<Array<main.ClientInfo>>;

export function DiscoverClients():Promise<Array<main.ClientInfo>>;

export function GetClientInfo(arg1:string):Promise<main.SystemInfo>;

export function GetScreenshot(arg1:string):Promise<string>;

export function GetStreamFrame(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function StartScreenStream(arg1:string,arg2:number):Promise<string>;

export function StopScreenStream(arg1:string):Promise<string>;
